all:
	g++ lazy-eval.cpp -o lazy -std=c++11
	g++ lazy-eval-tmpl.cpp -o tmpl -std=c++11
	g++ foo.cpp -o foo -std=c++11
	g++ foo_tmpl.cpp -o foo_tmpl -std=c++11
	g++ foo_tmpl_op.cpp -o op -std=c++11
	g++ vector.cpp -o vector -std=c++11
clean:
	@rm -f lazy tmpl foo foo_tmpl op vector
